spring.application.name=WhiteRigEngine

# DATABASE
spring.datasource.url=jdbc:postgresql://localhost:5432/whiterig_db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=SecretKeyWhiteRigEngineFullStackDeveloperCapstone2026SuperSecureKey!
jwt.expirationMs=86400000